setup-cml and setup-dvc with cml-runner update
iterative/cml_cloud_case pull request #6
Opened 2021-02-09 15:27 UTC by DavidGOrtega

Update to be using setup-cml with cml-runner

2022-09-26 19:11 UTC, 0x2b3bfa0 requested changes

2022-09-26 19:11 UTC, 0x2b3bfa0 commented on .github/workflows/cml.yaml
> +          node-version: '12'
`-Wprehistoric-node-version`

2022-09-26 19:11 UTC, 0x2b3bfa0 commented on .github/workflows/cml.yaml
> +      image: dvcorg/cml-py3
`-Wrancid-container-image`

2022-09-27 15:03 UTC, closed without merging

2022-09-27 15:03 UTC, DavidGOrtega commented
Not relevant any more